/**
 * ! STANDARD OUTPUT IN LINUX
 * when a program is executed in terminal it generates output
 * that can be displayed directly in terminal window
 * this is known as standard output
 *
 *
 * ! BASIC EXAMPLE
 * ls
 *
 * - ls command output terminal pe show karega
 *
 *
 * ! REDIRECTION OF OUTPUT
 * ls > a.txt
 *
 * - ls ka output a.txt mein chala jayega
 * - agar file exist nahi karti toh new file create ho jayegi
 *
 *
 * ! TWO TYPES OF REDIRECTION
 *
 * >
 * - overwrite karta hai
 *
 * >>
 * - append karta hai
 * - overwrite nahi karta
 *
 *
 * ! ECHO EXAMPLE
 * echo "hello" > a.txt
 *
 * - a.txt mein hello likh jayega
 *
 *
 * echo "world" >> a.txt
 *
 * - existing content ke baad append hoga
 *
 *
 * ! STANDARD ERROR
 * ls -z
 *
 * - invalid option hai
 * - error generate karega
 *
 *
 * ls -z 2> e.txt
 *
 * - error terminal pe show nahi hoga
 * - e.txt mein store ho jayega
 *
 *
 * ! WHY 2> WORKS
 * Linux mein internally:
 *
 * 1
 * - standard output (stdout)
 *
 * 2
 * - standard error (stderr)
 *
 *
 * normally:
 * ls > a.txt
 *
 * actually:
 * 1> a.txt
 *
 * hota hai
 *
 *
 * ! MEANING OF 1 AND 2
 *
 * 1>
 * - standard output redirect karta hai
 *
 * 2>
 * - standard error redirect karta hai
 *
 *
 * ! REDIRECT BOTH OUTPUT AND ERROR
 * Example:
 *
 * ls hello -z > out.txt 2> err.txt
 *
 * - normal output out.txt mein jayega
 * - errors err.txt mein jayenge
 *
 *
 * ! IMPORTANT CORRECTION
 * Original notes mein:
 *
 * ls -z> hello.txt 2>bye.txt
 *
 * isme spacing aur syntax issue tha
 *
 * correct readable syntax:
 *
 * ls -z > hello.txt 2> bye.txt
 *
 *
 * ! IMPORTANT NOTE
 * shell pehle poora command execute karta hai
 * then stdout aur stderr ko respective files mein redirect karta hai
 *
 *
 * ! COMMON USE CASES
 * - log files save karna
 * - errors alag store karna
 * - debugging
 * - command output capture karna
 *
 *
 * ! IMPORTANT NOTES
 * stdout
 * - normal output
 *
 * stderr
 * - error output
 *
 * >
 * - overwrite redirect
 *
 * >>
 * - append redirect
 *
 * 2>
 * - error redirect
 *
 *
 * ! SUMMARY OF THIS LECTURE
 * Commands learned:
 * ls > a.txt
 * echo "hello" > a.txt
 * echo "world" >> a.txt
 * ls -z 2> e.txt
 * ls hello -z > out.txt 2> err.txt
 *
 * Concepts learned:
 * - standard output
 * - standard error
 * - overwrite vs append
 * - output redirection
 * - error redirection
 *
 *
 * ! INTERVIEW QUESTIONS FROM THIS LECTURE
 *
 * 1) What is standard output in Linux?
 * Answer:
 * - Normal output generated by a command.
 *
 *
 * 2) What does > do in Linux?
 * Answer:
 * - Redirects output and overwrites file content.
 *
 *
 * 3) What does >> do in Linux?
 * Answer:
 * - Appends output without overwriting.
 *
 *
 * 4) What is stdout?
 * Answer:
 * - Standard output stream.
 *
 *
 * 5) What is stderr?
 * Answer:
 * - Standard error stream.
 *
 *
 * 6) What does 2> mean?
 * Answer:
 * - Redirects standard error.
 *
 *
 * 7) What does:
 * ls > a.txt
 * do?
 *
 * Answer:
 * - Stores ls output into a.txt
 *
 *
 * 8) What happens if redirected file does not exist?
 * Answer:
 * - Linux creates the file automatically.
 *
 *
 * 9) Difference between stdout and stderr?
 * Answer:
 * - stdout stores normal output
 * - stderr stores error messages
 *
 *
 * 10) What does this command do?
 * ls hello -z > out.txt 2> err.txt
 *
 * Answer:
 * - Normal output goes to out.txt
 * - Errors go to err.txt
 *
 */